### ISSUE TITLE
 git clone --filter=blob:none --quiet 'https://****@github.com/app-generator/priv-django-admin-black-pro' 'C:\Users\marco\AppData\Local\Temp\pip-req-build-nill3rv6' did not run successfully.   │ exit code: 128

### ISSUE THREAD

**Issue by marcosturbonett** [creativetimofficial/ct-black-dashboard-pro-django#1]
We followed all the installation steps, but the process is reporting this error:

git clone --filter=blob:none --quiet 'https://****@github.com/app-generator/priv-django-admin-black-pro' 'C:\Users\marco\AppData\Local\Temp\pip-req-build-nill3rv6' did not run successfully.
  │ exit code: 128

**Comment by app-generator** [comment]
Hello @marcosturbonett 

Thank you for using our products.

The installation fails because the `GITHUB_TOKEN` is not exported to the environment. 
The token basically unlocks access to this private repository: 

`git+https://${GITHUB_TOKEN}@github.com/app-generator/priv-django-admin-black-pro`

In order to unblock your development, please do:

- Access your `Creative-tim` account 
- Navigate to `my purchases` section
- Download the build instructions via `CODE` button
- Unzip and open the Markdown file
- Export the `GITHUB_TOKEN` in the environment
- Re-run the packages installation 

At this point, the set up should be successful. 

Let us know if worked. 

P.S. Here is a video tutorial that explains the product compilation and LIVE Deploy:

👉 [Django Black PRO - How to use It .. and Go LIVE](https://www.youtube.com/watch?v=5BgutmR77F8)

**Comment by marcosturbonett** [comment]
I did all the steps in the video and tutorial, but it asks for a password.
I use other templates with the same access method and they are all working perfectly.

**Comment by app-generator** [comment]
Hello @marcosturbonett 

The password popup is asked because the `GITHUB_TOKEN` is not exported in the environment. 
Please note that this product is a premium one and a purchase is required in order to get the GITHUB_TOKEN. 

As mentioned before, the GITHUB_TOKEN that unlocks the full access can be found by downloading the product archive on Creative-Tim. 

P.S. Please confirm if you own a license for this product. 

Adrian @  **Creative-Tim** Support

**Comment by marcosturbonett** [comment]
Hi Again, good morning.
The environment variable was created correctly. I can display its contents normally with the command: 
(venv) ➜ echo $GITHUB_TOKEN

that the correct token is displayed:
ghp_************************rhbj

**Comment by kargerova** [comment]
Hallo everyone,
I have the same issue using kaniko (https://docs.gitlab.com/ee/ci/docker/using_kaniko.html)

Running other project e.g. django-admin-soft-pro with kaniko works fine.
Running project django-admin-black-pro from my local computer with powershell runns fine too 🙂

Is there any update please?

Best regards
Lenka

**Comment by murffious** [comment]
> I did all the steps in the video and tutorial, but it asks for a password. I use other templates with the same access method and they are all working perfectly.

I have the same issue. It may have to do with your ssh vs https github set up I am trying to solve as well. I use MFA. 
my terminal said
remote: Support for password authentication was removed on August 13, 2021.

it may be why:
Two-Factor Authentication

If you have 2FA enabled, you'll need to generate an app password (or use your regular password if prompted) after entering the token in the clone URL.
Example:

Bash
git clone https://ghp_YOUR_TOKEN@github.com/yourusername/yourrepo.git
Use code [with caution.](https://github.com/faq#coding)

Replace ghp_YOUR_TOKEN, yourusername, and yourrepo with your actual values


I cannot seem to use the GITHUB token and my APP token here... they are like the same thing 

remote: Repository not found.
fatal: repository 'https://github.com/app-generator/priv-django-admin-black-pro/' not found

**Comment by app-generator** [comment]
Hello @murffious 

In order to use it, the GITHUB_TOKEN needs to be exported into the environment. 

For LIVE help, feel free to join Discord:

https://discord.gg/fZC6hup

Ty!

**Comment by murffious** [comment]
> > I did all the steps in the video and tutorial, but it asks for a password. I use other templates with the same access method and they are all working perfectly.
> 
> I have the same issue. It may have to do with your ssh vs https github set up I am trying to solve as well. I use MFA. my terminal said remote: Support for password authentication was removed on August 13, 2021.
> 
> it may be why: Two-Factor Authentication
> 
> If you have 2FA enabled, you'll need to generate an app password (or use your regular password if prompted) after entering the token in the clone URL. Example:
> 
> Bash git clone https://[ghp_YOUR_TOKEN@github.com](mailto:ghp_YOUR_TOKEN@github.com)/yourusername/yourrepo.git Use code [with caution.](https://github.com/faq#coding)
> 
> Replace ghp_YOUR_TOKEN, yourusername, and yourrepo with your actual values
> 
> I cannot seem to use the GITHUB token and my APP token here... they are like the same thing
> 
> remote: Repository not found. fatal: repository 'https://github.com/app-generator/priv-django-admin-black-pro/' not found

solved. thanks to app-generaor
